version: '3'

services:
  marklogic-server:
    image: store/marklogicdb/marklogic-server:10.0-2-dev-ubi
    environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=admin
        - MARKLOGIC_ADMIN_PASSWORD=admin
        - TZ=Europe/Prague
    ports:
     - 7997-8030:7997-8030
  mysql-server:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
     MYSQL_USER: 'gnasri'
      # You can use whatever password you like
     MYSQL_PASSWORD: 'admin'
      # Password for root access
     MYSQL_ROOT_PASSWORD: 'admin'
   ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
   expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
   volumes:
     - my-db:/var/lib/mysql
  
volumes:
 my-db:
      